on:
  push:
    branches:
      - master
name: Build and Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:  ${{ secrets.cluster_url }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        local-dir: ./build/
        server-dir: ./www_wei/